apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ts-microservice
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ekyamuran/beamer
    targetRevision: main
    path: charts/beamer
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ts-microservice

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
