{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "ts-microservice.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "ts-microservice.labels" . | nindent 4 }}
imagePullSecrets:
{{- toYaml .Values.imagePullSecrets | nindent 2 }}
{{- end }}
